name = "stashit-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Auth Database (shared by all users)
[[d1_databases]]
binding = "AUTH_DB"
database_name = "stashit-auth"
database_id = "1e950ca2-6104-4298-bd85-4c6a65d83145"

# Template Database (for creating new user DBs)
[[d1_databases]]
binding = "DB"
database_name = "stashit-template"
database_id = "0d088c9a-f54e-4c76-8215-a2a3b9c5fd18"

[vars]
NODE_ENV = "development"